# Generated by Django 3.2.5 on 2022-01-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('usn', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('dislikes', models.ManyToManyField(related_name='dislikes', to='material.Material')),
                ('likes', models.ManyToManyField(related_name='likes', to='material.Material')),
                ('material', models.ManyToManyField(to='material.Material')),
            ],
        ),
        migrations.CreateModel(
            name='issues',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('issue_status', models.CharField(blank=True, max_length=100)),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_view.member')),
            ],
        ),
    ]
