# Generated by Django 3.2.5 on 2022-01-20 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20220119_1946'),
        ('user_view', '0002_auto_20220119_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='time_s',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='report',
            field=models.ManyToManyField(related_name='report', to='material.Material'),
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=100)),
                ('notification_desc', models.TextField(blank=True)),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_view.member')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
