# Generated by Django 3.2.5 on 2022-01-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='material',
            table='material',
        ),
    ]
