# Generated by Django 3.2.5 on 2022-01-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_material_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
